// Generated by Bisonc++ V5.02.00 on Thu, 21 Nov 2019 17:00:05 -0500

// $insert class.ih
#include "ltspice_symbol_parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {289, 0}, // 1: ltspicesymbolfile ->  <empty>
     {289, 2}, // 2: ltspicesymbolfile ('\x0a') ->  ltspicesymbolfile '\x0a'
     {289, 3}, // 3: ltspicesymbolfile ->  ltspicesymbolfile header body
     {290, 2}, // 4: header ('\x0a') ->  header '\x0a'
     {290, 2}, // 5: header ->  versionline symboltypeline
     {291, 4}, // 6: versionline (VERSION) ->  VERSION ' ' integer '\x0a'
     {292, 4}, // 7: symboltypeline (SYMBOLTYPE) ->  SYMBOLTYPE ' ' string '\x0a'
     {293, 2}, // 8: body ->  body body
     {293, 1}, // 9: body ->  lineline
     {293, 1}, // 10: body ->  rectangleline
     {293, 1}, // 11: body ->  circleline
     {293, 1}, // 12: body ->  arcline
     {293, 1}, // 13: body ->  textline
     {293, 1}, // 14: body ->  windowline
     {293, 1}, // 15: body ->  symattrline
     {293, 1}, // 16: body ->  pinlines
     {294, 12}, // 17: lineline (LINE) ->  LINE ' ' string ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {294, 14}, // 18: lineline (LINE) ->  LINE ' ' string ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {295, 12}, // 19: rectangleline (RECTANGLE) ->  RECTANGLE ' ' string ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {296, 12}, // 20: circleline (CIRCLE) ->  CIRCLE ' ' string ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {296, 14}, // 21: circleline (CIRCLE) ->  CIRCLE ' ' string ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {297, 20}, // 22: arcline (ARC) ->  ARC ' ' string ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {297, 21}, // 23: arcline (ARC) ->  ARC ' ' string integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {298, 12}, // 24: textline (TEXT) ->  TEXT ' ' integer ' ' integer ' ' string ' ' integer ' ' string '\x0a'
     {299, 12}, // 25: windowline (WINDOW) ->  WINDOW ' ' integer ' ' integer ' ' integer ' ' string ' ' integer '\x0a'
     {300, 2}, // 26: symattrline ('\x0a') ->  symattrstring '\x0a'
     {301, 3}, // 27: symattrstring (' ') ->  symattrstring ' ' string
     {301, 3}, // 28: symattrstring (' ') ->  symattrstring ' ' integer
     {301, 2}, // 29: symattrstring (' ') ->  symattrstring ' '
     {301, 1}, // 30: symattrstring (SYMATTR) ->  SYMATTR
     {302, 2}, // 31: pinlines ->  pinlines pinattrline
     {302, 1}, // 32: pinlines ->  pinline
     {303, 10}, // 33: pinline (PIN) ->  PIN ' ' integer ' ' integer ' ' string ' ' integer '\x0a'
     {304, 2}, // 34: pinattrline ('\x0a') ->  pinattrstring '\x0a'
     {305, 3}, // 35: pinattrstring (' ') ->  pinattrstring ' ' string
     {305, 3}, // 36: pinattrstring (' ') ->  pinattrstring ' ' integer
     {305, 2}, // 37: pinattrstring (' ') ->  pinattrstring ' '
     {305, 1}, // 38: pinattrstring (PINATTR) ->  PINATTR
     {306, 1}, // 39: string (STRING) ->  STRING
     {307, 1}, // 40: integer (INT) ->  INT
     {308, 1}, // 41: ltspicesymbolfile_$ ->  ltspicesymbolfile
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { DEF_RED}, {  2} },                     
    { {     289}, {  1} }, // ltspicesymbolfile
    { {       0}, { -1} },                     
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            6} },               
    { {        10}, {            2} }, // '\x0a'     
    { {       290}, {            3} }, // header     
    { {       291}, {            4} }, // versionline
    { {       259}, {            5} }, // VERSION    
    { {     _EOF_}, { PARSE_ACCEPT} },               
    { {         0}, {            0} },               
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 21} },                 
    { {       293}, {  6} }, // body         
    { {        10}, {  7} }, // '\x0a'       
    { {       294}, {  8} }, // lineline     
    { {       295}, {  9} }, // rectangleline
    { {       296}, { 10} }, // circleline   
    { {       297}, { 11} }, // arcline      
    { {       298}, { 12} }, // textline     
    { {       299}, { 13} }, // windowline   
    { {       300}, { 14} }, // symattrline  
    { {       302}, { 15} }, // pinlines     
    { {       261}, { 16} }, // LINE         
    { {       262}, { 17} }, // RECTANGLE    
    { {       263}, { 18} }, // CIRCLE       
    { {       264}, { 19} }, // ARC          
    { {       265}, { 20} }, // TEXT         
    { {       266}, { 21} }, // WINDOW       
    { {       301}, { 22} }, // symattrstring
    { {       303}, { 23} }, // pinline      
    { {       267}, { 24} }, // SYMATTR      
    { {       268}, { 25} }, // PIN          
    { {         0}, {  0} },                 
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       292}, { 26} }, // symboltypeline
    { {       260}, { 27} }, // SYMBOLTYPE    
    { {         0}, {  0} },                  
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 28} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_6[] =
{
    { { REQ_DEF}, { 20} },                 
    { {     293}, { 29} }, // body         
    { {     294}, {  8} }, // lineline     
    { {     295}, {  9} }, // rectangleline
    { {     296}, { 10} }, // circleline   
    { {     297}, { 11} }, // arcline      
    { {     298}, { 12} }, // textline     
    { {     299}, { 13} }, // windowline   
    { {     300}, { 14} }, // symattrline  
    { {     302}, { 15} }, // pinlines     
    { {     261}, { 16} }, // LINE         
    { {     262}, { 17} }, // RECTANGLE    
    { {     263}, { 18} }, // CIRCLE       
    { {     264}, { 19} }, // ARC          
    { {     265}, { 20} }, // TEXT         
    { {     266}, { 21} }, // WINDOW       
    { {     301}, { 22} }, // symattrstring
    { {     303}, { 23} }, // pinline      
    { {     267}, { 24} }, // SYMATTR      
    { {     268}, { 25} }, // PIN          
    { {       0}, { -3} },                 
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_11[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_12[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_15[] =
{
    { { REQ_DEF}, {   4} },                 
    { {     304}, {  30} }, // pinattrline  
    { {     305}, {  31} }, // pinattrstring
    { {     269}, {  32} }, // PINATTR      
    { {       0}, { -16} },                 
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 33} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 34} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 35} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 36} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 37} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 38} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {        10}, { 39} }, // '\x0a'
    { {        32}, { 40} }, // ' '   
    { {         0}, {  0} },          
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 41} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_26[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 42} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 43} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_29[] =
{
    { { REQ_DEF}, { 20} },                 
    { {     293}, { 29} }, // body         
    { {     294}, {  8} }, // lineline     
    { {     295}, {  9} }, // rectangleline
    { {     296}, { 10} }, // circleline   
    { {     297}, { 11} }, // arcline      
    { {     298}, { 12} }, // textline     
    { {     299}, { 13} }, // windowline   
    { {     300}, { 14} }, // symattrline  
    { {     302}, { 15} }, // pinlines     
    { {     261}, { 16} }, // LINE         
    { {     262}, { 17} }, // RECTANGLE    
    { {     263}, { 18} }, // CIRCLE       
    { {     264}, { 19} }, // ARC          
    { {     265}, { 20} }, // TEXT         
    { {     266}, { 21} }, // WINDOW       
    { {     301}, { 22} }, // symattrstring
    { {     303}, { 23} }, // pinline      
    { {     267}, { 24} }, // SYMATTR      
    { {     268}, { 25} }, // PIN          
    { {       0}, { -8} },                 
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {        10}, { 45} }, // '\x0a'
    { {        32}, { 46} }, // ' '   
    { {         0}, {  0} },          
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       306}, { 47} }, // string
    { {       257}, { 48} }, // STRING
    { {         0}, {  0} },          
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       306}, { 49} }, // string
    { {       257}, { 48} }, // STRING
    { {         0}, {  0} },          
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       306}, { 50} }, // string
    { {       257}, { 48} }, // STRING
    { {         0}, {  0} },          
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       306}, { 51} }, // string
    { {       257}, { 48} }, // STRING
    { {         0}, {  0} },          
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 52} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 53} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_40[] =
{
    { { REQ_DEF}, {   5} },           
    { {     306}, {  54} }, // string 
    { {     307}, {  55} }, // integer
    { {     257}, {  48} }, // STRING 
    { {     258}, {  44} }, // INT    
    { {       0}, { -29} },           
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 56} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       306}, { 57} }, // string
    { {       257}, { 48} }, // STRING
    { {         0}, {  0} },          
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {        10}, { 58} }, // '\x0a'
    { {         0}, {  0} },          
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_46[] =
{
    { { REQ_DEF}, {   5} },           
    { {     306}, {  59} }, // string 
    { {     307}, {  60} }, // integer
    { {     257}, {  48} }, // STRING 
    { {     258}, {  44} }, // INT    
    { {       0}, { -37} },           
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 61} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 62} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 63} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  4} },           
    { {        32}, { 64} }, // ' '    
    { {       307}, { 65} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 66} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 67} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 68} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {        10}, { 69} }, // '\x0a'
    { {         0}, {  0} },          
};

SR__ s_58[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 70} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 71} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 72} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 73} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 74} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 75} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 76} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 77} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_69[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 78} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 79} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 80} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 81} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 82} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 83} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 84} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 85} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 86} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 87} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 88} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 89} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 90} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       306}, { 91} }, // string
    { {       257}, { 48} }, // STRING
    { {         0}, {  0} },          
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 92} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       306}, { 93} }, // string
    { {       257}, { 48} }, // STRING
    { {         0}, {  0} },          
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 94} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 95} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 96} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 97} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       307}, { 98} }, // integer
    { {       258}, { 44} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 99} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 100} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 101} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 102} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 103} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 104} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_97[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 105} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 106} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_99[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 107} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {   3} },          
    { {       306}, { 108} }, // string
    { {       257}, {  48} }, // STRING
    { {         0}, {   0} },          
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 109} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 110} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_103[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 111} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 112} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_105[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 113} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_106[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 114} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_107[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 115} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_108[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 116} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_109[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 117} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 118} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_111[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 119} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_112[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 120} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 121} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_114[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 122} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_115[] =
{
    { { REQ_TOKEN}, {   3} },          
    { {       306}, { 123} }, // string
    { {       257}, {  48} }, // STRING
    { {         0}, {   0} },          
};

SR__ s_116[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 124} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_118[] =
{
    { { REQ_TOKEN}, {   3} },          
    { {        10}, { 125} }, // '\x0a'
    { {        32}, { 126} }, // ' '   
    { {         0}, {   0} },          
};

SR__ s_119[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 127} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {   3} },          
    { {        10}, { 128} }, // '\x0a'
    { {        32}, { 129} }, // ' '   
    { {         0}, {   0} },          
};

SR__ s_121[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 130} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_122[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 131} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_123[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 132} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_124[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 133} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_125[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_126[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 134} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_127[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_128[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_129[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 135} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_130[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 136} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_131[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 137} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_132[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_133[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_134[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 138} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_135[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 139} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_136[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 140} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_137[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 141} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_138[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_139[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_140[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 142} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_141[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 143} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_142[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 144} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_143[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 145} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_144[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 146} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_145[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 147} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_146[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 148} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_147[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 149} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_148[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 150} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_149[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 151} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_150[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 152} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_151[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       307}, { 153} }, // integer
    { {       258}, {  44} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_152[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_153[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 154} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_154[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,  s_153,  s_154,
};

} // anonymous namespace ends




// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

LTSpiceSymbolParserBase::LTSpiceSymbolParserBase()
:
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void LTSpiceSymbolParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void LTSpiceSymbolParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

void LTSpiceSymbolParser::print__()
{
// $insert print
}

void LTSpiceSymbolParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void LTSpiceSymbolParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack__.size();
    if (static_cast<size_t>(d_stackIdx__ + 1) == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack__.resize(newSize);
        if (d_valueStack__.capacity() >= newSize)
            d_valueStack__.resize(newSize);
        else
        {
            std::vector<STYPE__> enlarged(newSize);
            for (size_t idx = 0; idx != currentSize; ++idx)
                enlarged[idx] = std::move(d_valueStack__[idx]);
            d_valueStack__.swap(enlarged);
        }
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = std::move(d_val__);
}

void LTSpiceSymbolParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = std::move(d_nextVal__);
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void LTSpiceSymbolParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = std::move(d_val__);
    d_token__ = token;
}
     
void LTSpiceSymbolParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t LTSpiceSymbolParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void LTSpiceSymbolParser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

    switch (production)
    {
        // $insert actioncases
        
        case 2:
#line 95 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-1];
        }
        break;

        case 3:
#line 97 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         delete d_vsp__[-1].u_str;
         }
        break;

        case 4:
#line 106 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-1];
        }
        break;

        case 5:
#line 108 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string( *(d_vsp__[-1].u_str) + *(d_vsp__[0].u_str) );
         delete d_vsp__[-1].u_str;
         delete d_vsp__[0].u_str;
         }
        break;

        case 6:
#line 116 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string("Version "+std::to_string(d_vsp__[-1].u_int)+"\n");
         }
        break;

        case 7:
#line 122 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string("SymbolType "+*(d_vsp__[-1].u_str)+"\n");
         delete d_vsp__[-1].u_str;
         }
        break;

        case 8:
#line 131 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         }
        break;

        case 9:
#line 136 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 10:
#line 138 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 11:
#line 140 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 12:
#line 142 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 13:
#line 144 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 14:
#line 146 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 15:
#line 148 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 16:
#line 150 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 17:
#line 154 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         std::shared_ptr<LinePrimitive> line = std::make_shared<LinePrimitive>();
         line->start(Coordinate((d_vsp__[-7].u_int)/3.0,(d_vsp__[-5].u_int)/3.0));
         line->end(Coordinate((d_vsp__[-3].u_int)/3.0,(d_vsp__[-1].u_int)/3.0));
         ogeom_.push_back(line);
         }
        break;

        case 18:
#line 163 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         
         std::shared_ptr<LinePrimitive> line = std::make_shared<LinePrimitive>();
         line->start(Coordinate((d_vsp__[-9].u_int)/3.0,(d_vsp__[-7].u_int)/3.0));
         line->end(Coordinate((d_vsp__[-5].u_int)/3.0,(d_vsp__[-3].u_int)/3.0));
         ogeom_.push_back(line);
         }
        break;

        case 19:
#line 174 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         std::shared_ptr<RectPrimitive> rect = std::make_shared<RectPrimitive>();
         rect->anchor(Coordinate((d_vsp__[-7].u_int)/3.0, (d_vsp__[-5].u_int)/3.0));
         rect->height((d_vsp__[-1].u_int-d_vsp__[-5].u_int)/3.0);
         rect->width((d_vsp__[-3].u_int-d_vsp__[-7].u_int)/3.0);
         ogeom_.push_back(rect);
         }
        break;

        case 20:
#line 185 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         std::shared_ptr<CirclePrimitive> circ = std::make_shared<CirclePrimitive>();
         circ->hradius( (d_vsp__[-3].u_int - d_vsp__[-7].u_int)/6.0 );
         circ->vradius((d_vsp__[-1].u_int-d_vsp__[-5].u_int)/6.0);
         circ->center( Coordinate( (d_vsp__[-7].u_int)/3.0 + circ->hradius(), (d_vsp__[-5].u_int)/3.0 + circ->vradius() ));
         ogeom_.push_back(circ);
         }
        break;

        case 21:
#line 195 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         std::shared_ptr<CirclePrimitive> circ = std::make_shared<CirclePrimitive>();
         circ->hradius( (d_vsp__[-5].u_int - d_vsp__[-9].u_int)/6.0 );
         circ->vradius((d_vsp__[-3].u_int-d_vsp__[-7].u_int)/6.0);
         circ->center( Coordinate( (d_vsp__[-9].u_int)/3.0 + circ->hradius(), (d_vsp__[-7].u_int)/3.0 + circ->vradius() ));
         ogeom_.push_back(circ);
         }
        break;

        case 22:
#line 206 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         
         std::shared_ptr<ArcPrimitive> arc = std::make_shared<ArcPrimitive>();
         arc->hradius( (d_vsp__[-11].u_int-d_vsp__[-15].u_int) / 6.0 );
         arc->vradius((d_vsp__[-9].u_int-d_vsp__[-13].u_int) / 6.0);
         arc->center( Coordinate( (d_vsp__[-15].u_int) / 3.0 + arc->hradius(), (d_vsp__[-13].u_int) / 3.0 + arc->vradius() ));
         
         
         Coordinate p1_abs((d_vsp__[-7].u_int)/3.0 - arc->center().x(), (d_vsp__[-5].u_int)/3.0 - arc->center().y());
         Coordinate p2_abs((d_vsp__[-3].u_int)/3.0 - arc->center().x(), (d_vsp__[-1].u_int)/3.0 - arc->center().y());
         float angle1 = std::atan2(p1_abs.y(),p1_abs.x()) / M_PI*180.0;
         float angle2 = std::atan2(p2_abs.y(),p2_abs.x()) / M_PI*180.0;
         
         arc->set_start_angle_degrees(angle2); 
         arc->set_end_angle_degrees(angle1);
         ogeom_.push_back(arc);
         }
        break;

        case 23:
#line 229 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         }
        break;

        case 24:
#line 235 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         }
        break;

        case 25:
#line 241 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         }
        break;

        case 26:
#line 247 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         }
        break;

        case 27:
#line 253 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-2];
        }
        break;

        case 28:
#line 255 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-2];
        }
        break;

        case 29:
#line 257 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-1];
        }
        break;

        case 30:
#line 259 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 31:
#line 263 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         }
        break;

        case 32:
#line 268 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         }
        break;

        case 33:
#line 274 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         std::shared_ptr<SymbolPin> pin1 = std::make_shared<SymbolPin>();
         pin1->pin_location(Coordinate((d_vsp__[-7].u_int)/3.0,(d_vsp__[-5].u_int)/3.0));
         opins_.push_back(pin1);
         }
        break;

        case 34:
#line 283 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         }
        break;

        case 35:
#line 289 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-2];
        }
        break;

        case 36:
#line 291 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-2];
        }
        break;

        case 37:
#line 293 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-1];
        }
        break;

        case 38:
#line 295 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 39:
#line 302 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = d_scanner.strVal();
         }
        break;

        case 40:
#line 308 "ltspice_symbol_parser.y"
        {
         d_val__.u_int = d_scanner.intVal();
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void LTSpiceSymbolParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void LTSpiceSymbolParser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int LTSpiceSymbolParser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void LTSpiceSymbolParser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int LTSpiceSymbolParser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



