// Generated by Bisonc++ V5.02.00 on Mon, 25 Nov 2019 21:47:48 -0500

// $insert class.ih
#include "ltspice_symbol_parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {307, 0}, // 1: ltspicesymbolfile ->  <empty>
     {307, 2}, // 2: ltspicesymbolfile ('\x0a') ->  ltspicesymbolfile '\x0a'
     {307, 3}, // 3: ltspicesymbolfile ->  ltspicesymbolfile header body
     {308, 2}, // 4: header ('\x0a') ->  header '\x0a'
     {308, 2}, // 5: header ->  versionline symboltypeline
     {309, 4}, // 6: versionline (VERSION) ->  VERSION ' ' integer '\x0a'
     {310, 4}, // 7: symboltypeline (SYMBOLTYPE) ->  SYMBOLTYPE ' ' string '\x0a'
     {311, 2}, // 8: body ->  body body
     {311, 1}, // 9: body ->  lineline
     {311, 1}, // 10: body ->  rectangleline
     {311, 1}, // 11: body ->  circleline
     {311, 1}, // 12: body ->  arcline
     {311, 1}, // 13: body ->  textline
     {311, 1}, // 14: body ->  windowline
     {311, 1}, // 15: body ->  symattrline
     {311, 1}, // 16: body ->  pinlines
     {312, 12}, // 17: lineline (LINE) ->  LINE ' ' string ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {312, 14}, // 18: lineline (LINE) ->  LINE ' ' string ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {313, 12}, // 19: rectangleline (RECTANGLE) ->  RECTANGLE ' ' string ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {314, 12}, // 20: circleline (CIRCLE) ->  CIRCLE ' ' string ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {314, 14}, // 21: circleline (CIRCLE) ->  CIRCLE ' ' string ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {315, 20}, // 22: arcline (ARC) ->  ARC ' ' string ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {315, 21}, // 23: arcline (ARC) ->  ARC ' ' string integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer ' ' integer '\x0a'
     {316, 12}, // 24: textline (TEXT) ->  TEXT ' ' integer ' ' integer ' ' string ' ' integer ' ' string '\x0a'
     {317, 12}, // 25: windowline (WINDOW) ->  WINDOW ' ' integer ' ' integer ' ' integer ' ' string ' ' integer '\x0a'
     {318, 2}, // 26: symattrline ('\x0a') ->  symattrprefixstring '\x0a'
     {318, 2}, // 27: symattrline ('\x0a') ->  symattrmodelstring '\x0a'
     {318, 2}, // 28: symattrline ('\x0a') ->  symattrvaluestring '\x0a'
     {318, 2}, // 29: symattrline ('\x0a') ->  symattrvalue2string '\x0a'
     {318, 2}, // 30: symattrline ('\x0a') ->  symattrspicelinestring '\x0a'
     {318, 2}, // 31: symattrline ('\x0a') ->  symattrspiceline2string '\x0a'
     {318, 2}, // 32: symattrline ('\x0a') ->  symattrdescriptionstring '\x0a'
     {318, 2}, // 33: symattrline ('\x0a') ->  symattrmodelfilestring '\x0a'
     {319, 2}, // 34: symattrprefixstring (' ') ->  symattrprefixstring ' '
     {319, 5}, // 35: symattrprefixstring (SYMATTR) ->  SYMATTR ' ' PREFIX ' ' string
     {320, 2}, // 36: symattrmodelstring (' ') ->  symattrmodelstring ' '
     {320, 5}, // 37: symattrmodelstring (SYMATTR) ->  SYMATTR ' ' SPICEMODEL ' ' string
     {321, 2}, // 38: symattrvaluestring ->  symattrvaluestring string
     {321, 2}, // 39: symattrvaluestring ->  symattrvaluestring integer
     {321, 2}, // 40: symattrvaluestring (' ') ->  symattrvaluestring ' '
     {321, 5}, // 41: symattrvaluestring (SYMATTR) ->  SYMATTR ' ' VALUE ' ' string
     {321, 5}, // 42: symattrvaluestring (SYMATTR) ->  SYMATTR ' ' VALUE ' ' integer
     {322, 2}, // 43: symattrvalue2string ->  symattrvalue2string string
     {322, 2}, // 44: symattrvalue2string ->  symattrvalue2string integer
     {322, 2}, // 45: symattrvalue2string (' ') ->  symattrvalue2string ' '
     {322, 5}, // 46: symattrvalue2string (SYMATTR) ->  SYMATTR ' ' VALUE2 ' ' string
     {322, 5}, // 47: symattrvalue2string (SYMATTR) ->  SYMATTR ' ' VALUE2 ' ' integer
     {323, 2}, // 48: symattrspicelinestring ->  symattrspicelinestring string
     {323, 2}, // 49: symattrspicelinestring ->  symattrspicelinestring integer
     {323, 2}, // 50: symattrspicelinestring (' ') ->  symattrspicelinestring ' '
     {323, 5}, // 51: symattrspicelinestring (SYMATTR) ->  SYMATTR ' ' SPICELINE ' ' string
     {323, 5}, // 52: symattrspicelinestring (SYMATTR) ->  SYMATTR ' ' SPICELINE ' ' integer
     {324, 2}, // 53: symattrspiceline2string ->  symattrspiceline2string string
     {324, 2}, // 54: symattrspiceline2string ->  symattrspiceline2string integer
     {324, 2}, // 55: symattrspiceline2string (' ') ->  symattrspiceline2string ' '
     {324, 5}, // 56: symattrspiceline2string (SYMATTR) ->  SYMATTR ' ' SPICELINE2 ' ' string
     {325, 2}, // 57: symattrdescriptionstring ->  symattrdescriptionstring string
     {325, 2}, // 58: symattrdescriptionstring ->  symattrdescriptionstring integer
     {325, 2}, // 59: symattrdescriptionstring (' ') ->  symattrdescriptionstring ' '
     {325, 5}, // 60: symattrdescriptionstring (SYMATTR) ->  SYMATTR ' ' DESCRIPTION ' ' string
     {326, 2}, // 61: symattrmodelfilestring ->  symattrmodelfilestring string
     {326, 2}, // 62: symattrmodelfilestring ->  symattrmodelfilestring integer
     {326, 5}, // 63: symattrmodelfilestring (SYMATTR) ->  SYMATTR ' ' MODELFILE ' ' string
     {327, 2}, // 64: pinlines ->  pinlines pinattrline
     {327, 1}, // 65: pinlines ->  pinline
     {328, 10}, // 66: pinline (PIN) ->  PIN ' ' integer ' ' integer ' ' string ' ' integer '\x0a'
     {329, 2}, // 67: pinattrline ('\x0a') ->  pinattrpinnamestring '\x0a'
     {329, 2}, // 68: pinattrline ('\x0a') ->  pinattrspiceorderstring '\x0a'
     {330, 2}, // 69: pinattrpinnamestring (' ') ->  pinattrpinnamestring ' '
     {330, 5}, // 70: pinattrpinnamestring (PINATTR) ->  PINATTR ' ' PINNAME ' ' integer
     {330, 5}, // 71: pinattrpinnamestring (PINATTR) ->  PINATTR ' ' PINNAME ' ' string
     {331, 2}, // 72: pinattrspiceorderstring (' ') ->  pinattrspiceorderstring ' '
     {331, 5}, // 73: pinattrspiceorderstring (PINATTR) ->  PINATTR ' ' SPICEORDER ' ' integer
     {332, 1}, // 74: string (STRING) ->  STRING
     {332, 1}, // 75: string ('-') ->  '-'
     {333, 1}, // 76: integer (INT) ->  INT
     {334, 1}, // 77: ltspicesymbolfile_$ ->  ltspicesymbolfile
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { DEF_RED}, {  2} },                     
    { {     307}, {  1} }, // ltspicesymbolfile
    { {       0}, { -1} },                     
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            6} },               
    { {        10}, {            2} }, // '\x0a'     
    { {       308}, {            3} }, // header     
    { {       309}, {            4} }, // versionline
    { {       259}, {            5} }, // VERSION    
    { {     _EOF_}, { PARSE_ACCEPT} },               
    { {         0}, {            0} },               
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 28} },                            
    { {       311}, {  6} }, // body                    
    { {        10}, {  7} }, // '\x0a'                  
    { {       312}, {  8} }, // lineline                
    { {       313}, {  9} }, // rectangleline           
    { {       314}, { 10} }, // circleline              
    { {       315}, { 11} }, // arcline                 
    { {       316}, { 12} }, // textline                
    { {       317}, { 13} }, // windowline              
    { {       318}, { 14} }, // symattrline             
    { {       327}, { 15} }, // pinlines                
    { {       261}, { 16} }, // LINE                    
    { {       262}, { 17} }, // RECTANGLE               
    { {       263}, { 18} }, // CIRCLE                  
    { {       264}, { 19} }, // ARC                     
    { {       265}, { 20} }, // TEXT                    
    { {       266}, { 21} }, // WINDOW                  
    { {       319}, { 22} }, // symattrprefixstring     
    { {       320}, { 23} }, // symattrmodelstring      
    { {       321}, { 24} }, // symattrvaluestring      
    { {       322}, { 25} }, // symattrvalue2string     
    { {       323}, { 26} }, // symattrspicelinestring  
    { {       324}, { 27} }, // symattrspiceline2string 
    { {       325}, { 28} }, // symattrdescriptionstring
    { {       326}, { 29} }, // symattrmodelfilestring  
    { {       328}, { 30} }, // pinline                 
    { {       267}, { 31} }, // SYMATTR                 
    { {       276}, { 32} }, // PIN                     
    { {         0}, {  0} },                            
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       310}, { 33} }, // symboltypeline
    { {       260}, { 34} }, // SYMBOLTYPE    
    { {         0}, {  0} },                  
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 35} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_6[] =
{
    { { REQ_DEF}, { 27} },                            
    { {     311}, { 36} }, // body                    
    { {     312}, {  8} }, // lineline                
    { {     313}, {  9} }, // rectangleline           
    { {     314}, { 10} }, // circleline              
    { {     315}, { 11} }, // arcline                 
    { {     316}, { 12} }, // textline                
    { {     317}, { 13} }, // windowline              
    { {     318}, { 14} }, // symattrline             
    { {     327}, { 15} }, // pinlines                
    { {     261}, { 16} }, // LINE                    
    { {     262}, { 17} }, // RECTANGLE               
    { {     263}, { 18} }, // CIRCLE                  
    { {     264}, { 19} }, // ARC                     
    { {     265}, { 20} }, // TEXT                    
    { {     266}, { 21} }, // WINDOW                  
    { {     319}, { 22} }, // symattrprefixstring     
    { {     320}, { 23} }, // symattrmodelstring      
    { {     321}, { 24} }, // symattrvaluestring      
    { {     322}, { 25} }, // symattrvalue2string     
    { {     323}, { 26} }, // symattrspicelinestring  
    { {     324}, { 27} }, // symattrspiceline2string 
    { {     325}, { 28} }, // symattrdescriptionstring
    { {     326}, { 29} }, // symattrmodelfilestring  
    { {     328}, { 30} }, // pinline                 
    { {     267}, { 31} }, // SYMATTR                 
    { {     276}, { 32} }, // PIN                     
    { {       0}, { -3} },                            
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_11[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_12[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_15[] =
{
    { { REQ_DEF}, {   5} },                           
    { {     329}, {  37} }, // pinattrline            
    { {     330}, {  38} }, // pinattrpinnamestring   
    { {     331}, {  39} }, // pinattrspiceorderstring
    { {     277}, {  40} }, // PINATTR                
    { {       0}, { -16} },                           
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 41} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 42} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 43} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 44} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 45} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 46} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {        10}, { 47} }, // '\x0a'
    { {        32}, { 48} }, // ' '   
    { {         0}, {  0} },          
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {        10}, { 49} }, // '\x0a'
    { {        32}, { 50} }, // ' '   
    { {         0}, {  0} },          
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  8} },           
    { {        10}, { 51} }, // '\x0a' 
    { {       332}, { 52} }, // string 
    { {       333}, { 53} }, // integer
    { {        32}, { 54} }, // ' '    
    { {       257}, { 55} }, // STRING 
    { {        45}, { 56} }, // '-'    
    { {       258}, { 57} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  8} },           
    { {        10}, { 58} }, // '\x0a' 
    { {       332}, { 59} }, // string 
    { {       333}, { 60} }, // integer
    { {        32}, { 61} }, // ' '    
    { {       257}, { 55} }, // STRING 
    { {        45}, { 56} }, // '-'    
    { {       258}, { 57} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  8} },           
    { {        10}, { 62} }, // '\x0a' 
    { {       332}, { 63} }, // string 
    { {       333}, { 64} }, // integer
    { {        32}, { 65} }, // ' '    
    { {       257}, { 55} }, // STRING 
    { {        45}, { 56} }, // '-'    
    { {       258}, { 57} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  8} },           
    { {        10}, { 66} }, // '\x0a' 
    { {       332}, { 67} }, // string 
    { {       333}, { 68} }, // integer
    { {        32}, { 69} }, // ' '    
    { {       257}, { 55} }, // STRING 
    { {        45}, { 56} }, // '-'    
    { {       258}, { 57} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  8} },           
    { {        10}, { 70} }, // '\x0a' 
    { {       332}, { 71} }, // string 
    { {       333}, { 72} }, // integer
    { {        32}, { 73} }, // ' '    
    { {       257}, { 55} }, // STRING 
    { {        45}, { 56} }, // '-'    
    { {       258}, { 57} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  7} },           
    { {        10}, { 74} }, // '\x0a' 
    { {       332}, { 75} }, // string 
    { {       333}, { 76} }, // integer
    { {       257}, { 55} }, // STRING 
    { {        45}, { 56} }, // '-'    
    { {       258}, { 57} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 77} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 78} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_33[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 79} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       333}, { 80} }, // integer
    { {       258}, { 57} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_36[] =
{
    { { REQ_DEF}, { 27} },                            
    { {     311}, { 36} }, // body                    
    { {     312}, {  8} }, // lineline                
    { {     313}, {  9} }, // rectangleline           
    { {     314}, { 10} }, // circleline              
    { {     315}, { 11} }, // arcline                 
    { {     316}, { 12} }, // textline                
    { {     317}, { 13} }, // windowline              
    { {     318}, { 14} }, // symattrline             
    { {     327}, { 15} }, // pinlines                
    { {     261}, { 16} }, // LINE                    
    { {     262}, { 17} }, // RECTANGLE               
    { {     263}, { 18} }, // CIRCLE                  
    { {     264}, { 19} }, // ARC                     
    { {     265}, { 20} }, // TEXT                    
    { {     266}, { 21} }, // WINDOW                  
    { {     319}, { 22} }, // symattrprefixstring     
    { {     320}, { 23} }, // symattrmodelstring      
    { {     321}, { 24} }, // symattrvaluestring      
    { {     322}, { 25} }, // symattrvalue2string     
    { {     323}, { 26} }, // symattrspicelinestring  
    { {     324}, { 27} }, // symattrspiceline2string 
    { {     325}, { 28} }, // symattrdescriptionstring
    { {     326}, { 29} }, // symattrmodelfilestring  
    { {     328}, { 30} }, // pinline                 
    { {     267}, { 31} }, // SYMATTR                 
    { {     276}, { 32} }, // PIN                     
    { {       0}, { -8} },                            
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -64} }, 
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {        10}, { 81} }, // '\x0a'
    { {        32}, { 82} }, // ' '   
    { {         0}, {  0} },          
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {        10}, { 83} }, // '\x0a'
    { {        32}, { 84} }, // ' '   
    { {         0}, {  0} },          
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        32}, { 85} }, // ' '
    { {         0}, {  0} },       
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  4} },          
    { {       332}, { 86} }, // string
    { {       257}, { 55} }, // STRING
    { {        45}, { 56} }, // '-'   
    { {         0}, {  0} },          
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  4} },          
    { {       332}, { 87} }, // string
    { {       257}, { 55} }, // STRING
    { {        45}, { 56} }, // '-'   
    { {         0}, {  0} },          
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  4} },          
    { {       332}, { 88} }, // string
    { {       257}, { 55} }, // STRING
    { {        45}, { 56} }, // '-'   
    { {         0}, {  0} },          
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  4} },          
    { {       332}, { 89} }, // string
    { {       257}, { 55} }, // STRING
    { {        45}, { 56} }, // '-'   
    { {         0}, {  0} },          
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       333}, { 90} }, // integer
    { {       258}, { 57} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       333}, { 91} }, // integer
    { {       258}, { 57} }, // INT    
    { {         0}, {  0} },           
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -74} }, 
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -75} }, 
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -76} }, 
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -62} }, 
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  9} },               
    { {       268}, { 92} }, // PREFIX     
    { {       269}, { 93} }, // SPICEMODEL 
    { {       270}, { 94} }, // VALUE      
    { {       271}, { 95} }, // VALUE2     
    { {       272}, { 96} }, // SPICELINE  
    { {       273}, { 97} }, // SPICELINE2 
    { {       274}, { 98} }, // DESCRIPTION
    { {       275}, { 99} }, // MODELFILE  
    { {         0}, {  0} },               
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 100} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {   4} },          
    { {       332}, { 101} }, // string
    { {       257}, {  55} }, // STRING
    { {        45}, {  56} }, // '-'   
    { {         0}, {   0} },          
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 102} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       278}, { 103} }, // PINNAME   
    { {       279}, { 104} }, // SPICEORDER
    { {         0}, {   0} },              
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 105} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 106} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 107} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {   4} },           
    { {        32}, { 108} }, // ' '    
    { {       333}, { 109} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 110} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 111} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 112} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 113} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 114} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 115} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 116} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_97[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 117} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 118} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_99[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 119} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 120} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 121} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_102[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_103[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 122} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 123} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_105[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 124} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_106[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 125} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_107[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 126} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_108[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 127} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_109[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 128} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 129} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_111[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 130} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_112[] =
{
    { { REQ_TOKEN}, {   4} },          
    { {       332}, { 131} }, // string
    { {       257}, {  55} }, // STRING
    { {        45}, {  56} }, // '-'   
    { {         0}, {   0} },          
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {   4} },          
    { {       332}, { 132} }, // string
    { {       257}, {  55} }, // STRING
    { {        45}, {  56} }, // '-'   
    { {         0}, {   0} },          
};

SR__ s_114[] =
{
    { { REQ_TOKEN}, {   6} },           
    { {       332}, { 133} }, // string 
    { {       333}, { 134} }, // integer
    { {       257}, {  55} }, // STRING 
    { {        45}, {  56} }, // '-'    
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_115[] =
{
    { { REQ_TOKEN}, {   6} },           
    { {       332}, { 135} }, // string 
    { {       333}, { 136} }, // integer
    { {       257}, {  55} }, // STRING 
    { {        45}, {  56} }, // '-'    
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_116[] =
{
    { { REQ_TOKEN}, {   6} },           
    { {       332}, { 137} }, // string 
    { {       333}, { 138} }, // integer
    { {       257}, {  55} }, // STRING 
    { {        45}, {  56} }, // '-'    
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_117[] =
{
    { { REQ_TOKEN}, {   4} },          
    { {       332}, { 139} }, // string
    { {       257}, {  55} }, // STRING
    { {        45}, {  56} }, // '-'   
    { {         0}, {   0} },          
};

SR__ s_118[] =
{
    { { REQ_TOKEN}, {   4} },          
    { {       332}, { 140} }, // string
    { {       257}, {  55} }, // STRING
    { {        45}, {  56} }, // '-'   
    { {         0}, {   0} },          
};

SR__ s_119[] =
{
    { { REQ_TOKEN}, {   4} },          
    { {       332}, { 141} }, // string
    { {       257}, {  55} }, // STRING
    { {        45}, {  56} }, // '-'   
    { {         0}, {   0} },          
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 142} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_121[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_122[] =
{
    { { REQ_TOKEN}, {   6} },           
    { {       333}, { 143} }, // integer
    { {       332}, { 144} }, // string 
    { {       258}, {  57} }, // INT    
    { {       257}, {  55} }, // STRING 
    { {        45}, {  56} }, // '-'    
    { {         0}, {   0} },           
};

SR__ s_123[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 145} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_124[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 146} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_125[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 147} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_126[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 148} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_127[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 149} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_128[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 150} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_129[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 151} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_130[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 152} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_131[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_132[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_133[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_134[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_135[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_136[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_137[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_138[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_139[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_140[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_141[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_142[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 153} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_143[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR__ s_144[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_145[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -73} }, 
};

SR__ s_146[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 154} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_147[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 155} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_148[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 156} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_149[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 157} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_150[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 158} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_151[] =
{
    { { REQ_TOKEN}, {   4} },          
    { {       332}, { 159} }, // string
    { {       257}, {  55} }, // STRING
    { {        45}, {  56} }, // '-'   
    { {         0}, {   0} },          
};

SR__ s_152[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 160} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_153[] =
{
    { { REQ_TOKEN}, {   4} },          
    { {       332}, { 161} }, // string
    { {       257}, {  55} }, // STRING
    { {        45}, {  56} }, // '-'   
    { {         0}, {   0} },          
};

SR__ s_154[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 162} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_155[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 163} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_156[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 164} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_157[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 165} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_158[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 166} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_159[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 167} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_160[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 168} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_161[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 169} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_162[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 170} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_163[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 171} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_164[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 172} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_165[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 173} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_166[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 174} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_167[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 175} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_168[] =
{
    { { REQ_TOKEN}, {   4} },          
    { {       332}, { 176} }, // string
    { {       257}, {  55} }, // STRING
    { {        45}, {  56} }, // '-'   
    { {         0}, {   0} },          
};

SR__ s_169[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 177} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_170[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 178} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_171[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 179} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_172[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 180} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_173[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 181} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_174[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 182} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_175[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 183} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_176[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 184} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_177[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 185} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_178[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 186} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_179[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 187} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_180[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 188} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_181[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 189} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_182[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 190} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_183[] =
{
    { { REQ_TOKEN}, {   4} },          
    { {       332}, { 191} }, // string
    { {       257}, {  55} }, // STRING
    { {        45}, {  56} }, // '-'   
    { {         0}, {   0} },          
};

SR__ s_184[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 192} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_185[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_186[] =
{
    { { REQ_TOKEN}, {   3} },          
    { {        10}, { 193} }, // '\x0a'
    { {        32}, { 194} }, // ' '   
    { {         0}, {   0} },          
};

SR__ s_187[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 195} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_188[] =
{
    { { REQ_TOKEN}, {   3} },          
    { {        10}, { 196} }, // '\x0a'
    { {        32}, { 197} }, // ' '   
    { {         0}, {   0} },          
};

SR__ s_189[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 198} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_190[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 199} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_191[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 200} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_192[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 201} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_193[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_194[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 202} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_195[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_196[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_197[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 203} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_198[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 204} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_199[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 205} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_200[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_201[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_202[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 206} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_203[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 207} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_204[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 208} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_205[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 209} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_206[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_207[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_208[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 210} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_209[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 211} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_210[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 212} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_211[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 213} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_212[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 214} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_213[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 215} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_214[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 216} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_215[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 217} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_216[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 218} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_217[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        32}, { 219} }, // ' '
    { {         0}, {   0} },       
};

SR__ s_218[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 220} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_219[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       333}, { 221} }, // integer
    { {       258}, {  57} }, // INT    
    { {         0}, {   0} },           
};

SR__ s_220[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_221[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 222} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_222[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,  s_153,  s_154,  s_155,  s_156,  s_157,  s_158,  s_159,
  s_160,  s_161,  s_162,  s_163,  s_164,  s_165,  s_166,  s_167,  s_168,  s_169,
  s_170,  s_171,  s_172,  s_173,  s_174,  s_175,  s_176,  s_177,  s_178,  s_179,
  s_180,  s_181,  s_182,  s_183,  s_184,  s_185,  s_186,  s_187,  s_188,  s_189,
  s_190,  s_191,  s_192,  s_193,  s_194,  s_195,  s_196,  s_197,  s_198,  s_199,
  s_200,  s_201,  s_202,  s_203,  s_204,  s_205,  s_206,  s_207,  s_208,  s_209,
  s_210,  s_211,  s_212,  s_213,  s_214,  s_215,  s_216,  s_217,  s_218,  s_219,
  s_220,  s_221,  s_222,
};

} // anonymous namespace ends




// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

LTSpiceSymbolParserBase::LTSpiceSymbolParserBase()
:
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void LTSpiceSymbolParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void LTSpiceSymbolParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

void LTSpiceSymbolParser::print__()
{
// $insert print
}

void LTSpiceSymbolParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void LTSpiceSymbolParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack__.size();
    if (static_cast<size_t>(d_stackIdx__ + 1) == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack__.resize(newSize);
        if (d_valueStack__.capacity() >= newSize)
            d_valueStack__.resize(newSize);
        else
        {
            std::vector<STYPE__> enlarged(newSize);
            for (size_t idx = 0; idx != currentSize; ++idx)
                enlarged[idx] = std::move(d_valueStack__[idx]);
            d_valueStack__.swap(enlarged);
        }
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = std::move(d_val__);
}

void LTSpiceSymbolParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = std::move(d_nextVal__);
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void LTSpiceSymbolParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = std::move(d_val__);
    d_token__ = token;
}
     
void LTSpiceSymbolParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t LTSpiceSymbolParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void LTSpiceSymbolParser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

    switch (production)
    {
        // $insert actioncases
        
        case 2:
#line 103 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-1];
        }
        break;

        case 3:
#line 105 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         delete d_vsp__[-1].u_str;
         }
        break;

        case 4:
#line 114 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-1];
        }
        break;

        case 5:
#line 116 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string( *(d_vsp__[-1].u_str) + *(d_vsp__[0].u_str) );
         delete d_vsp__[-1].u_str;
         delete d_vsp__[0].u_str;
         }
        break;

        case 6:
#line 124 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string("Version "+std::to_string(d_vsp__[-1].u_int)+"\n");
         }
        break;

        case 7:
#line 130 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string("SymbolType "+*(d_vsp__[-1].u_str)+"\n");
         delete d_vsp__[-1].u_str;
         }
        break;

        case 8:
#line 139 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         }
        break;

        case 9:
#line 144 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 10:
#line 146 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 11:
#line 148 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 12:
#line 150 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 13:
#line 152 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 14:
#line 154 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 15:
#line 156 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 16:
#line 158 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[0];
        }
        break;

        case 17:
#line 162 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         std::shared_ptr<LinePrimitive> line = std::make_shared<LinePrimitive>();
         line->start(Coordinate((d_vsp__[-7].u_int)/LTSPICE_SCALE_FACTOR,(d_vsp__[-5].u_int)/LTSPICE_SCALE_FACTOR));
         line->end(Coordinate((d_vsp__[-3].u_int)/LTSPICE_SCALE_FACTOR,(d_vsp__[-1].u_int)/LTSPICE_SCALE_FACTOR));
         ogeom_.push_back(line);
         }
        break;

        case 18:
#line 171 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         
         std::shared_ptr<LinePrimitive> line = std::make_shared<LinePrimitive>();
         line->start(Coordinate((d_vsp__[-9].u_int)/LTSPICE_SCALE_FACTOR,(d_vsp__[-7].u_int)/LTSPICE_SCALE_FACTOR));
         line->end(Coordinate((d_vsp__[-5].u_int)/LTSPICE_SCALE_FACTOR,(d_vsp__[-3].u_int)/LTSPICE_SCALE_FACTOR));
         ogeom_.push_back(line);
         }
        break;

        case 19:
#line 182 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         std::shared_ptr<RectPrimitive> rect = std::make_shared<RectPrimitive>();
         rect->anchor(Coordinate((d_vsp__[-7].u_int)/LTSPICE_SCALE_FACTOR, (d_vsp__[-5].u_int)/LTSPICE_SCALE_FACTOR));
         rect->height((d_vsp__[-1].u_int-d_vsp__[-5].u_int)/LTSPICE_SCALE_FACTOR);
         rect->width((d_vsp__[-3].u_int-d_vsp__[-7].u_int)/LTSPICE_SCALE_FACTOR);
         ogeom_.push_back(rect);
         }
        break;

        case 20:
#line 193 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         std::shared_ptr<CirclePrimitive> circ = std::make_shared<CirclePrimitive>();
         circ->hradius( (d_vsp__[-3].u_int - d_vsp__[-7].u_int)/2.0 / LTSPICE_SCALE_FACTOR);
         circ->vradius((d_vsp__[-1].u_int-d_vsp__[-5].u_int)/2.0 / LTSPICE_SCALE_FACTOR);
         circ->center( Coordinate( (d_vsp__[-7].u_int)/LTSPICE_SCALE_FACTOR + circ->hradius(), (d_vsp__[-5].u_int)/LTSPICE_SCALE_FACTOR + circ->vradius() ));
         ogeom_.push_back(circ);
         }
        break;

        case 21:
#line 203 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         std::shared_ptr<CirclePrimitive> circ = std::make_shared<CirclePrimitive>();
         circ->hradius( (d_vsp__[-5].u_int - d_vsp__[-9].u_int)/2.0 / LTSPICE_SCALE_FACTOR );
         circ->vradius((d_vsp__[-3].u_int-d_vsp__[-7].u_int)/2.0 / LTSPICE_SCALE_FACTOR);
         circ->center( Coordinate( (d_vsp__[-9].u_int)/LTSPICE_SCALE_FACTOR + circ->hradius(), (d_vsp__[-7].u_int)/LTSPICE_SCALE_FACTOR + circ->vradius() ));
         ogeom_.push_back(circ);
         }
        break;

        case 22:
#line 214 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         
         std::shared_ptr<ArcPrimitive> arc = std::make_shared<ArcPrimitive>();
         arc->hradius( (d_vsp__[-11].u_int-d_vsp__[-15].u_int) / 2.0 / LTSPICE_SCALE_FACTOR );
         arc->vradius((d_vsp__[-9].u_int-d_vsp__[-13].u_int) / 2.0 / LTSPICE_SCALE_FACTOR);
         arc->center( Coordinate( (d_vsp__[-15].u_int) / LTSPICE_SCALE_FACTOR + arc->hradius(), (d_vsp__[-13].u_int) / LTSPICE_SCALE_FACTOR + arc->vradius() ));
         
         
         Coordinate p1_abs((d_vsp__[-7].u_int)/LTSPICE_SCALE_FACTOR - arc->center().x(), (d_vsp__[-5].u_int)/LTSPICE_SCALE_FACTOR - arc->center().y());
         Coordinate p2_abs((d_vsp__[-3].u_int)/LTSPICE_SCALE_FACTOR - arc->center().x(), (d_vsp__[-1].u_int)/LTSPICE_SCALE_FACTOR - arc->center().y());
         float angle1 = std::atan2(p1_abs.y(),p1_abs.x()) / M_PI*180.0;
         float angle2 = std::atan2(p2_abs.y(),p2_abs.x()) / M_PI*180.0;
         
         arc->set_start_angle_degrees(angle2); 
         arc->set_end_angle_degrees(angle1);
         ogeom_.push_back(arc);
         }
        break;

        case 23:
#line 237 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         }
        break;

        case 24:
#line 243 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         }
        break;

        case 25:
#line 249 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         switch(d_vsp__[-9].u_int)
         {
         case 0:
         
         osymbol_.set_attribute_show_on_schematic("INSTNAME",true);
         osymbol_.set_attribute_text_position("INSTNAME",Coordinate(d_vsp__[-7].u_int / LTSPICE_SCALE_FACTOR,d_vsp__[-5].u_int / LTSPICE_SCALE_FACTOR));
         break;
         case 1:
         
         break;
         case 3:
         
         osymbol_.set_attribute_show_on_schematic("VALUE",true);
         osymbol_.set_attribute_text_position("VALUE",Coordinate(d_vsp__[-7].u_int / LTSPICE_SCALE_FACTOR,d_vsp__[-5].u_int / LTSPICE_SCALE_FACTOR));
         break;
         case 38:
         
         osymbol_.set_attribute_show_on_schematic("SPICEMODEL",true);
         osymbol_.set_attribute_text_position("SPICEMODEL",Coordinate(d_vsp__[-7].u_int / LTSPICE_SCALE_FACTOR,d_vsp__[-5].u_int / LTSPICE_SCALE_FACTOR));
         break;
         case 39:
         
         osymbol_.set_attribute_show_on_schematic("SPICELINE",true);
         osymbol_.set_attribute_text_position("SPICELINE",Coordinate(d_vsp__[-7].u_int / LTSPICE_SCALE_FACTOR,d_vsp__[-5].u_int / LTSPICE_SCALE_FACTOR));
         break;
         case 40:
         
         break;
         case 123:
         
         break;
         }
         }
        break;

        case 26:
#line 287 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         osymbol_.set_attribute_value("PREFIX",*(d_vsp__[-1].u_str));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 27:
#line 294 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         osymbol_.set_attribute_value("SPICEMODEL",*(d_vsp__[-1].u_str));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 28:
#line 301 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         osymbol_.set_attribute_value("VALUE",*(d_vsp__[-1].u_str));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 29:
#line 308 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         delete d_vsp__[-1].u_str;
         }
        break;

        case 30:
#line 314 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         osymbol_.set_attribute_value("SPICELINE",*(d_vsp__[-1].u_str));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 31:
#line 321 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         delete d_vsp__[-1].u_str;
         }
        break;

        case 32:
#line 327 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         osymbol_.set_attribute_value("DESCRIPTION",*(d_vsp__[-1].u_str));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 33:
#line 334 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         osymbol_.set_attribute_value("MODELFILE",*(d_vsp__[-1].u_str));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 34:
#line 342 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-1];
        }
        break;

        case 35:
#line 344 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = d_vsp__[0].u_str;
         }
        break;

        case 36:
#line 350 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-1];
        }
        break;

        case 37:
#line 352 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = d_vsp__[0].u_str;
         }
        break;

        case 38:
#line 358 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + *(d_vsp__[0].u_str));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 39:
#line 364 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + std::to_string(d_vsp__[0].u_int));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 40:
#line 370 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + " ");
         delete d_vsp__[-1].u_str;
         }
        break;

        case 41:
#line 376 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = d_vsp__[0].u_str;
         }
        break;

        case 42:
#line 381 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(std::to_string(d_vsp__[0].u_int));
         }
        break;

        case 43:
#line 387 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + *(d_vsp__[0].u_str));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 44:
#line 393 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + std::to_string(d_vsp__[0].u_int));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 45:
#line 399 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + " ");
         delete d_vsp__[-1].u_str;
         }
        break;

        case 46:
#line 405 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = d_vsp__[0].u_str;
         }
        break;

        case 47:
#line 410 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(std::to_string(d_vsp__[0].u_int));
         }
        break;

        case 48:
#line 416 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + *(d_vsp__[0].u_str));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 49:
#line 422 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + std::to_string(d_vsp__[0].u_int));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 50:
#line 428 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + " ");
         delete d_vsp__[-1].u_str;
         }
        break;

        case 51:
#line 434 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = d_vsp__[0].u_str;
         }
        break;

        case 52:
#line 439 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(std::to_string(d_vsp__[0].u_int));
         }
        break;

        case 53:
#line 445 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + *(d_vsp__[0].u_str));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 54:
#line 451 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + std::to_string(d_vsp__[0].u_int));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 55:
#line 457 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + " ");
         delete d_vsp__[-1].u_str;
         }
        break;

        case 56:
#line 463 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = d_vsp__[0].u_str;
         }
        break;

        case 57:
#line 469 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + *(d_vsp__[0].u_str));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 58:
#line 475 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + std::to_string(d_vsp__[0].u_int));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 59:
#line 481 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + " ");
         delete d_vsp__[-1].u_str;
         }
        break;

        case 60:
#line 487 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = d_vsp__[0].u_str;
         }
        break;

        case 61:
#line 493 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + *(d_vsp__[0].u_str));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 62:
#line 499 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(*(d_vsp__[-1].u_str) + std::to_string(d_vsp__[0].u_int));
         delete d_vsp__[-1].u_str;
         }
        break;

        case 63:
#line 505 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = d_vsp__[0].u_str;
         }
        break;

        case 64:
#line 512 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         }
        break;

        case 65:
#line 517 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         }
        break;

        case 66:
#line 524 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         std::shared_ptr<SymbolPin> pin1 = std::make_shared<SymbolPin>();
         pin1->pin_location(Coordinate((d_vsp__[-7].u_int)/LTSPICE_SCALE_FACTOR,(d_vsp__[-5].u_int)/LTSPICE_SCALE_FACTOR));
         opins_.push_back(pin1);
         }
        break;

        case 67:
#line 534 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         if(!opins_.empty())
         (*(opins_.end()-1))->set_attribute_value("NAME",*(d_vsp__[-1].u_str));
         else
         std::cout << "WARNING: Pin attribute found but no pins added.\n";
         delete d_vsp__[-1].u_str;
         }
        break;

        case 68:
#line 544 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = nullptr;
         if(!opins_.empty())
         (*(opins_.end()-1))->set_attribute_value("SPICE_ORDER",std::to_string(d_vsp__[-1].u_int));
         else
         std::cout << "WARNING: Pin attribute found but no pins added.\n";
         }
        break;

        case 69:
#line 555 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-1];
        }
        break;

        case 70:
#line 557 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = new std::string(std::to_string(d_vsp__[0].u_int));
         }
        break;

        case 71:
#line 562 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = d_vsp__[0].u_str;
         }
        break;

        case 72:
#line 569 "ltspice_symbol_parser.y"
        {
            d_val__ = d_vsp__[-1];
        }
        break;

        case 73:
#line 571 "ltspice_symbol_parser.y"
        {
         d_val__.u_int = d_vsp__[0].u_int;
         }
        break;

        case 74:
#line 580 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = d_scanner.strVal();
         }
        break;

        case 75:
#line 585 "ltspice_symbol_parser.y"
        {
         d_val__.u_str = d_scanner.strVal();
         }
        break;

        case 76:
#line 591 "ltspice_symbol_parser.y"
        {
         d_val__.u_int = d_scanner.intVal();
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void LTSpiceSymbolParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void LTSpiceSymbolParser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int LTSpiceSymbolParser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void LTSpiceSymbolParser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int LTSpiceSymbolParser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



